---
- name: Switch to the admin context on Cisco ASA
  hosts: cisco_asa
  gather_facts: no
  tasks:
    - name: Enter enable mode
      cisco.asa.asa_command:
        commands:
          - enable
        prompt: 'Password:'
        answer: '{{ enable_password }}'
      register: enable_mode_output

    - name: Verify enable mode
      cisco.asa.asa_command:
        commands:
          - show curpriv
      register: current_privilege

    - name: Switch to system context
      cisco.asa.asa_command:
        commands:
          - changeto system
      register: system_context_output

    - name: Show context
      cisco.asa.asa_command:
        commands:
          - show context
      register: show_context_output

    - name: Parse admin context
      set_fact:
        admin_context: "{{ show_context_output.stdout[0].split('\n') | select('search', '\\*') | list | first | regex_search('^(\\*\\s+)?(\\S+)', '\\2') }}"

    - name: Switch to admin context
      cisco.asa.asa_command:
        commands:
          - "changeto context {{ admin_context }}"

    - name: Verify the current context
      cisco.asa.asa_command:
        commands:
          - show curpriv
      register: current_privilege

    - debug:
        msg: "Switched to context: {{ admin_context }}. Current privilege: {{ current_privilege.stdout[0] }}"
